### ISSUE TITLE
Don't serve markdown to clients that only want plain text

### ISSUE THREAD

**Issue by jaredly** [jaredly/reason-language-server#10]
- [x] parse `hover/contentFormat`
- [x] parse `completion/completionItem/documentationFormat`
- [x] convert markdown & ocamldoc comments to plaintext (see https://github.com/jaredly/reason-language-server/pull/14#issuecomment-396799625)

**Comment by gaelduplessix** [comment]
I'm not sure how to implement the distinction between hover and completion docs. As I understand, docs are cached when generated in [`newDocs`](https://github.com/jaredly/reason-language-server/blob/master/src/analyze/State.re#L48), which can be called either for a completion or a hover request.
So in order to serve, let's say, markdown for a hover and text for a completion, we would need to either:
- cache both text and markdown version of the docs
- cache an intermediate representation and generate text/markdown when requested
- keep caching markdown and convert to text with `Omd.to_text` when requested

I'm not really convinced by any of these options so I'm wondering if it's worth supporting such a use case.

Do you have a better option in mind ? Or is it ok to fallback to text if editor doesn't support markdown everywhere ?

**Comment by jaredly** [comment]
Hmmm yeah that is annoying. Let's go with "if they want plaintext anywhere, they get it everywhere". So we can have a single `clientNeedsPlainText` flag
