### ISSUE TITLE
Support for OCaml 4.7?

### ISSUE THREAD

**Issue by nikgraf** [jaredly/reason-language-server#238]
While this PR https://github.com/jaredly/reason-language-server/pull/167 should have added support for OCaml 4.7 for some reason it doesn't work with this repository https://github.com/revery-ui/revery-quick-start

Steps to reproduce:

1. Add the project
```
git clone https://github.com/revery-ui/revery-quick-start
cd revery-quick-start
esy install
esy code .
```
2. Open `App.re` in VS Code

<img width="756" alt="screenshot 2019-02-02 at 11 51 24" src="https://user-images.githubusercontent.com/223045/52163391-accb1c00-26e1-11e9-9337-1b733cf933d9.png">

**Comment by anmonteiro** [comment]
@nikgraf this doesn't look to be related to the OCaml 4.07 upgrade, as this project is running OCaml 4.07 itself and RLS works on itself. 

I found that the revery quick start project has the source files located in the project root itself, instead of in a `src` dir for example. #239 adds support for that pattern, which I suppose we hadn't found yet!

Could you try #239 locally and check if it fixes things for you?
