### ISSUE TITLE
Duplicate key in JSON message

### ISSUE THREAD

**Issue by slonoed** [jaredly/reason-language-server#290]
I use https://github.com/natebosch/vim-lsc client with VIM. I throw an error when a server sends a notification, because of keys duplication in JSON.

https://github.com/jaredly/reason-language-server/blob/master/src/lsp/Main.re#L74

**Comment by stouf** [comment]
Same problem with vim-ale: https://github.com/w0rp/ale/pull/2431#issuecomment-495450918

**Comment by rphuber** [comment]
Same issue for me with ale. Any updates on this?

**Comment by WhiskeyTuesday** [comment]
slonoed, stouf is it working for you now? I'm still not getting ALE to work with this, even with the new version 1.7.1 on linux.

**Comment by stouf** [comment]
@WhiskeyTuesday No, it's not working for me either. But in my case it could be unrelated to this project because the Ocaml Language Server used to work but doesn't anymore 😞 Does the Ocaml Language Server work for you?

**Comment by WhiskeyTuesday** [comment]
@stouf I haven't tried the Ocaml server, but I did notice that as of 70973c `src/lsp/main.re` lines 40 and 41 are identical. I haven't looked at any of the code closely, nor do I know anything about the lsp spec, so I don't know if that's a problem or not but it does seem to be duplicate JSON, which I understand was the original problem.

**Comment by stouf** [comment]
Hmm, I'm unfortunately not very familiar with the LSP protocol and this repository myself either to be honest 😕 Maybe @jaredly can help and answer your questions about those two duplicate lines and the consequences it could have?

As for why it still doesn't work with ALE, do you see any error message when you open a ReasonML file? When I posted [the comment above](https://github.com/jaredly/reason-language-server/issues/290#issuecomment-495451104), I was getting an error message from ALE complaining about the duplicate keys when opening a ReasonML file. I don't see anything now though; I don't even see the language server in the list of the processes running on my machine, which makes me believe the issue is probably not related to this repository in my case 😅
