### ISSUE TITLE
Jump to definition broken (tried native and bucklescript) in v1.7.2

### ISSUE THREAD

**Issue by cristianoc** [jaredly/reason-language-server#357]
Tried jump to definition on genType, both the tool itself (native) and one of the example projects (uses bucklescript).
Jump to definition seems broken. And works when reverting to v1.7.1.

**Comment by cristianoc** [comment]
```
Read message 
{"jsonrpc":"2.0","id":4,"method":"textDocument/definition","params":{"textDocument":{"uri":"file:///Users/cristianoc/reasonml/genType/examples/typescript-react-example/src/A.re"},"position":{"line":2,"character":9}}}
[server] Got a method textDocument/definition
[server] processing took 0.00405311584473ms
Sending response {"id": 4, "jsonrpc": "2.0", "result": null}
```

**Comment by cristianoc** [comment]
Bisected to this diff:
https://github.com/jaredly/reason-language-server/commit/7db4260b4739620f1cba6997b1687cc13bfcba3a

+ @anmonteiro 

Repro:
```reasonml
let x = 1;

let y = x + 1;
```

cmd/click on x in the second line

**Comment by jaredly** [comment]
ooh thanks for tracking this down!

**Comment by PierreGuttAlive** [comment]
The same here. Couple days ago my vscode updated and also it updated all my extensions. With 1.7.2 i can't properly jump to definition. Seems like downgrade to 1.7.1 fixed this issue

**Comment by cristianoc** [comment]
@jaredly do you reckon there's a not-too-cumbersome way to add tests for things of this kind?

**Comment by jchavarri** [comment]
I took a quick look, not sure where the problem is, but for the code @cristianoc [mentioned above](https://github.com/jaredly/reason-language-server/issues/357#issuecomment-557871052) everything goes well until this call to `hashFind`:

https://github.com/jaredly/reason-language-server/blob/0b3226a4d6735f71ca418a5b11c8152a6d10d38b/core/Query.re#L209

it seems the `stamps.values` hashmap does not contain the value for that key 🤔 They get added in `ProcessCmt` right?

**Comment by jaredly** [comment]
@cristianoc yeah I'll see about adding a test for this -- I do have "jump to definition" tests in place, i'll see why this isn't being caught

**Comment by cristianoc** [comment]
Broken for everything except 4.08: https://github.com/jaredly/reason-language-server/commit/7db4260b4739620f1cba6997b1687cc13bfcba3a#r36373778.
