### ISSUE TITLE
Unbound modules in bs-dev-dependencies

### ISSUE THREAD

**Issue by thangngoc89** [jaredly/reason-language-server#67]
When I define a module inside `bs-dev-dependencies`, lsp doesn't seem to understand it and said it's unbound. Move them to `bs-dependencies` as a temporary fix

**Comment by jaredly** [comment]
This should be a pretty quick fix -- the change would be here: https://github.com/jaredly/reason-language-server/blob/master/src/util/FindFiles.re#L63

**Comment by no-stack-dub-sack** [comment]
I am interested in learning more about Reason and contributing to OS projects like this (especially because I need good Windows support to be able to pitch using Reason at work!), but i'm still quite new to the language. Are you saying this is because there is no `Json.get("bs-dev-dependencies")` here? will that fix the issue?

I'd like to take this on if I can understand it a bit better. Thanks!

**Comment by jaredly** [comment]
I *think* that adding something like this should do the trick, but it would require testing to make sure everything happens as expected.
```
let devDeps = config |> Json.get("bs-dev-dependencies") |?> Json.array |? [] |> optMap(Json.string);
let deps = deps @ devDeps;
```
